### PR TITLE
Fix: OlFeature do not create a new Feature on props.properties change

### LINKED ISSUE #128: Icons disappearing for features that have custom properties
The icons for features are disappearing on subsequent loads when there are properties defined on them.

For example:

```
      <ol-vector-layer>
        <ol-source-vector ref="airframesFlightsSourceVector">
          <ol-feature v-for="flight in props.airframesFlights" :key="`airframes_flight_${flight.id}`" :properties="{ id: flight.id, featureType: 'airframes-flight', icon: aircraftIcon, airframesFlightId: flight.id }">
            <ol-geom-point :coordinates="[flight.longitude, flight.latitude]" />
            <ol-style>
              <ol-style-icon
                :src="aircraftIcon"
                :anchor="[0.5, 0.5]"
                :scale="0.05"
                :rotation="flight.track"
                />
            </ol-style>
          </ol-feature>
        </ol-source-vector>
      </ol-vector-layer>
```

### PR DESCRIPTION
**Pull request by mathiash98**
Creating a new Feature results in removing any styling that has been applied to the feature. This can also be solved by adding more reactivity on the injected styledObj in OlStyle.

Please make sure that I do not break anything by removing the usage of `usePropsAsObjectProperties`. I did not figure out what it adds of value in this component. Is it possible to pass in the coordinates of the feature into the props.properties object? -> If so, then I break the functionality here

See https://github.com/MelihAltintas/vue3-openlayers/issues/128#issuecomment-1630472490 for details

Fixes #128

### CODE REVIEW

File: src/components/map/OlFeature.vue [hunk 1]
```diff
@@ -34,15 +33,16 @@ const animation = inject<Ref<FeatureAnimation | null> | null>(
...
-  vectorSource?.value?.removeFeature(oldVal);
-  vectorSource?.value?.addFeature(newVal);
-  vectorSource?.value?.changed();
-});
+watch(
+  () => props.properties, // Needed as props.properties is optional
+  () => {
+    // Ensure the feature's properties are updated on change
+    feature.value.setProperties(props.properties);
+    console.debug("feature changed", feature.value.getProperties().lat);
```
Comment (mathiash98) [inline src/components/map/OlFeature.vue:43]:
```suggestion
```
Delete console debug
